---
####### head node play ############
- name: Head node configuration
  become: yes
  hosts: head
  connection: local
  tags: head_node_play
  roles:
      - crb
      - timesync
      - head-node_pkg_inst
      - head-node_nfs_server

####### compute node play ########
- name: Compute node configuration
  become: yes
  hosts: all_nodes
  tags: compute_node_play
  roles:
      - crb
      - timesync
      - compute-node_pkg_inst
      - compute-node_autofs
