  - name: Copy compute node RPMs to /tmp for installation
    ansible.builtin.copy: 
      src: "{{ item }}"
      dest: /tmp
    with_items:
      - slurm-{{ slurm_vers }}-1.el8.x86_64.rpm
      - slurm-perlapi-{{ slurm_vers }}-1.el8.x86_64.rpm
      - slurm-slurmd-{{ slurm_vers }}-1.el8.x86_64.rpm
      - slurm-libpmi-{{ slurm_vers }}-1.el8.x86_64.rpm

  - name: Install compute node RPMs
    ansible.builtin.dnf:
      name: "/tmp/{{ item }}" 
      disable_gpg_check: yes
      state: present
    with_items:
      - slurm-{{ slurm_vers }}-1.el8.x86_64.rpm
      - slurm-perlapi-{{ slurm_vers }}-1.el8.x86_64.rpm
      - slurm-slurmd-{{ slurm_vers }}-1.el8.x86_64.rpm
      - slurm-libpmi-{{ slurm_vers }}-1.el8.x86_64.rpm

  - name: Create & change ownership of /etc/slurm/
    ansible.builtin.file:
      path: /etc/slurm
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Copy slurm.conf into place with correct permissions
    ansible.builtin.template:
     src: slurm.conf.j2
     dest: /etc/slurm/slurm.conf
     owner: slurm
     group: slurm
     mode: '0755'

  - name: Copy cgroup.conf into place with correct permissions
    ansible.builtin.copy:
     src: cgroup.conf
     dest: /etc/slurm/

  - name: Restart slurmd service
    ansible.builtin.service:
     name: slurmd
     enabled: yes
     state: restarted
