---
- name: Install OpenMPI on all nodes
  hosts: head:all_nodes
  gather_facts: no
  tasks:

    - name: Install OpenMPI via DNF
      ansible.builtin.dnf:
        name: openmpi-devel
        state: present
