  - name: Install RPMs on the head node 
    ansible.builtin.dnf:
      name: "/tmp/rpmbuild/RPMS/x86_64/{{ item }}" 
      disable_gpg_check: yes
      state: present
    with_items:
      - slurm-{{ slurm_vers }}-1.el9.x86_64.rpm
      - slurm-example-configs-{{ slurm_vers }}-1.el9.x86_64.rpm
      - slurm-slurmctld-{{ slurm_vers }}-1.el9.x86_64.rpm
      - slurm-slurmdbd-{{ slurm_vers }}-1.el9.x86_64.rpm
      - slurm-perlapi-{{ slurm_vers }}-1.el9.x86_64.rpm
      - slurm-libpmi-{{ slurm_vers }}-1.el9.x86_64.rpm
      - slurm-devel-{{ slurm_vers }}-1.el9.x86_64.rpm

  - name: Copying slurm.conf into place with correct permissions
    ansible.builtin.template:
     src: roles/slurmd/templates/slurm.conf.j2
     dest: /etc/slurm/slurm.conf
     owner: slurm
     group: slurm
     mode: '0755'

  - name: Copying slurmdbd.conf into place with correct permissions
    ansible.builtin.template:
     src: roles/slurmd/templates/slurmdbd.conf.j2
     dest: /etc/slurm/slurmdbd.conf
     owner: slurm
     group: slurm
     mode: '0600'

  - name: Copying cgroup.conf into place with correct permissions
    ansible.builtin.copy:
     src: roles/slurmd/files/cgroup.conf
     dest: /etc/slurm/
     mode: '0755'

  - name: Copying mariadb-server.cnf into place
    ansible.builtin.copy:
     src: roles/slurmd/files/mariadb-server.cnf
     dest: /etc/my.cnf.d/
     owner: root 
     group: root 
