- name: Checking to see if the slurm .tar.bz2 file exists
  ansible.builtin.stat:
    path: roles/slurm-rpm-build/files/slurm-{{ slurm_vers }}.tar.bz2
  register: file_tar

- name: If it does not exist, pull latest version of slurm down
  ansible.builtin.command:
    cmd: wget https://download.schedmd.com/slurm/slurm-{{ slurm_vers }}.tar.bz2 -P roles/slurm-rpm-build/files 
  when: not file_tar.stat.exists

- name: Checking to see if the slurm rpms have already been created
  ansible.builtin.stat:
    path: /tmp/rpmbuild/RPMS/x86_64/slurm-example-configs-{{ slurm_vers }}-1.el9.x86_64.rpm
  register: file_rpm

- name: Building slurm rpms, this will skip if they are already built
  ansible.builtin.command:
    cmd: rpmbuild --define "_topdir /tmp/rpmbuild" --define '_with_pmix --with-pmix' -ta roles/slurm-rpm-build/files/slurm-{{ slurm_vers }}.tar.bz2 --with mysql --nodeps  
  when: not file_rpm.stat.exists

