- name: Enable the EPEL repo
  ansible.builtin.dnf:
     name: epel-release
     state: latest

- name: Enable the CRB repo (formerly powertools in Rocky Linux 9)
  ansible.builtin.command:
     cmd: dnf config-manager --set-enabled crb
